version: '3'
services:
  supportly-backend:
    container_name: supportly-backend
    image: jerrybraun17/supportly-backend:latest
    ports:
      - "8080:8080"
      - "9090:9090"
    restart: unless-stopped
    environment:
      - SUPPORTLY_MAIL_USERNAME
      - SUPPORTLY_MAIL_PASSWORD
      - SUPPORTLY_MYSQL_URL
      - SUPPORTLY_MYSQL_USER
      - SUPPORTLY_MYSQL_PASSWORD
      - SUPPORTLY_AZURE_CONNECTION_STRING
      - MEILI_MASTER_KEY
      - SUPPORTLY_JWT_SECRET
      - SUPPORTLY_SEARCH_API_URL
      - SUPPORTLY_FRONTEND_URL
      - SUPPORTLY_CORS
    networks:
      - supportly_network

  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.2.0-rc.4
    environment:
      - MEILI_MASTER_KEY
    volumes:
      - ./meili_data:/meili_data
    restart: unless-stopped
    networks:
      - supportly_network

volumes:
  meili_data:

networks:
  supportly_network:
    driver: bridge