version: '3'
services:
  supportly-backend:
    container_name: supportly-backend
    image: jerrybraun17/supportly-backend:latest
    build:
      context: .
    ports:
      - "8080:8080"
      - "9090:9090"
    restart: unless-stopped
    networks:
      - supportly_network

  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.2.0-rc.4
    environment:
      - MEILI_MASTER_KEY=GOChGlk8hDDaZCJ4MnzabhfhH2vJ_Pe18vUTU_wYiSI
    ports:
      - "7700:7700"
    volumes:
      - ./data/meili_data:/meili_data
    restart: unless-stopped
    networks:
      - supportly_network

volumes:
  meili_data:

networks:
  supportly_network:
    driver: bridge
