### Login
POST {{apiUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "DExc2OLmWOT4Rk2"
}

> {%
 client.global.set("accessToken", response.body.accessToken)
%}

### Create a user
POST {{apiUrl}}/auth/register
Content-Type: application/json

{
  "email": "test@supportly.beer",
  "firstName": "Max",
  "lastName": "Mustermann",
  "password": "Abcdefg",
  "profilePictureUrl": "https://picture.url"
}