### Login
POST {{apiUrl}}/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "12345678"
}

> {%
    client.global.set("token", response.body.token)
%}

### Create a user
POST {{apiUrl}}/auth/register
Content-Type: application/json

{
  "email": "user@example.com",
  "firstName": "Schurli",
  "lastName": "Yeeterich",
  "password": "12345678",
  "profilePictureUrl": "https://media.istockphoto.com/id/1200677760/photo/portrait-of-handsome-smiling-young-man-with-crossed-arms.jpg?s=612x612&w=0&k=20&c=g_ZmKDpK9VEEzWw4vJ6O577ENGLTOcrvYeiLxi8mVuo="
}

### Verify twofa
POST {{apiUrl}}/auth/twofa
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "admin@example.com",
  "token": "101857"
}