### Join Chat Room / Create Chat Room
GRPC localhost:9090/beer.supportly.chat.ChatService/JoinChatRoom

{
  "roomId": "TICKET-1",
  "userId": "1"
}

### Broadcast Message to Room
GRPC localhost:9090/beer.supportly.chat.ChatService/SendMessage

{
  "roomId": "TICKET-1",
  "senderId": "1",
  "senderDisplayName": "Jerro",
  "message": "Hello World",
  "timestamp": "1684848635976"
}

### Leave Chat Room
GRPC localhost:9090/beer.supportly.chat.ChatService/LeaveChatroom

{
  "roomId": "TICKET-1",
  "userId": "1"
}